### ISSUE TITLE
How to specify a particular culture media in the seeds.sbml file ?

### ISSUE THREAD

**Issue by alimatai** [cfrioux/miscoto#10]
Hello,

Is it possible to specify a culture media directly with its biocyc ID in the seeds.sbml file ? Like [this one](https://biocyc.org/ECOLI/NEW-IMAGE?type=Growth-Media&object=MIX0-806), for example.

Thanks.

**Comment by cfrioux** [comment]
Hi,

No there is no possibility to automatize this step at the moment.
Keep in mind that in any case the quantity of each nutriment is not taken into MiSCoTo as it performs qualitative analyses.

**Comment by alimatai** [comment]
Okay :/

In this case, do you know if there is a way to get the IDs of all the components of the mixtures of the media (i.e tryptone and yeast extract) ? 

Thanks.

**Comment by cfrioux** [comment]
Tryptone and yeast extracts are _non-defined mixtures_. They provide vitamins, peptides and other nutrients but we do not know exactly their contents.

**Comment by alimatai** [comment]
Allright, i'll do without it then.
